# Site
repository: MichielMurphy/MichielMurphy.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Michiel Murphy
title: Junior Mobile & Enterprise Developer
email: michiel_murphy@outlook.com
# website: https://michielmurphy.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  MichielMurphy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: michielmurphy
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Bekijk CV
    icon: fas fa-file-pdf
    url: /CV_Michiel_Murphy.pdf
#  - title: itsgoingto.be
#   icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Over mij
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hallo, ik ben Michiel en ik ben een Junior Software Developer. Dankzij mijn opleidingen en stage kan ik zelfstandig aan de slag en heb ik inzicht ontwikkeld in probleemoplossend denken. Mijn passie ligt bij het coderen. Ik ben iemand die de lat hoog legt voor zichzelf. Bovendien geef ik niet rap op en probeer ik steeds het beste van mezelf te geven.

  Zoals terug te vinden op mijn curriculum vitae ben ik gedurende mijn studies met verschillende frameworks aan de slag gegaan. Ik ben het meest bekwaam in: <mark>Java</mark>

content:
 # - title: Projects # Title for the section
 #   layout: list # Type of content section (list/text)
 #   content:
 #     - layout: top-middle
 #       title: Super awesome project
 #       link: github.com/sproogen
        # link_text: Project Website
 #       additional_links:
 #         - title:  sproogen/modern-resume-theme
 #           icon: fab fa-github
 #           url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
 #       quote: >
 #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
 #       description: | # this will include new lines to allow paragraphs
 #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Ervaring # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Signpost BV
        link: https://signpost.be/nl-be/
        # link_text: boringcompany.com
        sub_title: Stagiair Full Stack Developer
        caption: begin oktober 2022 - eind december 2022
        quote: >
           Een bedrijf met hoofdzetel in Lokeren, gespecialiseerd in het leveren en installeren van IT-infrastructuur (hardware en software) voor het onderwijs.
        description: | # this will include new lines to allow paragraphs
            Het onderhouden, uitbreiden en opstarten van projecten in een web development team met zes developers en twee project managers. De backend was in PhP en de frontend in React. Een van de features die ik van nul uitgewerkt heb, is het beheren en maken van een blogpagina: [Signpost Academy Blog](https://signpostacademy.eu/blog/)

  - title: Opleiding # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hogeschool Gent
        caption: 2020 - 2022
        sub_title: Graduaat Programmeren
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Tijdens deze opleiding leerde ik desktopapplicaties ontwikkelen met C#, traditionele webapplicaties uitwerken met behulp van HTML, CSS en JS, en single-page applicaties creëren met React. Daarnaast ging ik op vlak van mobiele applicaties te werk met React Native.
      - layout: left
        title: Hogeschool Gent
        caption: 2023 - 2025
        sub_title: Verkort Traject Bachelor Toegepaste Informatica
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Na het behalen van de graduaatsopleiding besloot ik om nog verder te studeren. Momenteel zit ik in het laatste jaar van een verkort traject van Bachelor Toegepaste Informatica. Ik heb gewerkt met volgende frameworks:
          - Android Jetpack Compose (Kotlin)
          - C# (.NET Core, Entity Framework, Blazor, LINQ)
          - Java (JavaFX, JPA, Spring Boot)
          - AngularJS

  - title: Extra
    layout: text
    content: | # this will include new lines to allow paragraphs
      Enkele andere interesses en hobby's:
      - Voetbal
      - Games
      - Festivals
      - Tuinieren

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
